name: test Build Mod
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    env:
      ANDROID_HOME: "E:/sdk"
      ANDROID_SDK_ROOT: "E:/sdk"

    steps:
      - uses: actions/checkout@v4

      - name: Add Android Tools to PATH
        shell: cmd
        run: echo E:\sdk\cmdline-tools\bin>>%GITHUB_PATH%

      - name: Build with Gradle
        shell: cmd
        run: gradlew.bat deploy

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnzipMeImNotAModModIsJarInsideMe
          path: build/libs/*.jar
