name: test Build Mod
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    env:
      ANDROID_HOME: "E:/sdk"
      ANDROID_SDK_ROOT: "E:/sdk"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: false

      - name: Build with Gradle for PC and Android
        shell: cmd
        run: gradlew.bat deploy -PandroidSdk="E:/sdk"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tetrator-j-Crossplatform
          path: build/libs/*.jar
