name: test Build Mod
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    env:
      ANDROID_HOME: "E:/sdk"
      ANDROID_SDK_ROOT: "E:/sdk"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: false

      - name: Build with Gradle
        shell: cmd
        run: gradlew.bat deploy
